{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:HelperTest", "name": "test_bytes", "time": 0.0005660057067871094, "type": "failure", "errtype": "builtins.AssertionError", "message": "b'hello world' != None", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/sapakusa/python-primer-jsong-pb-denver-070918/test/index_test.py\", line 9, in test_bytes\n    self.assertEqual(b, str_to_bytes(s))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: b'hello world' != None\n"}]}